### ISSUE TITLE
2.4.6 syntax error

### ISSUE THREAD

**Issue by Flash100** [LiveHelperChat/livehelperchat#901]
When trying upgrade.php or trying to access chat list:

Parse error: syntax error, unexpected '[' in /livehelp/lib/models/lhchat/erlhcoreclassmodelchatonlineuser.php on line 703

Showing no visitors on site and on front end, the widget now just spins if trying to open a chat.

**Comment by remdex** [comment]
fixed. It's not a bug you just needed higher php version. In any case updated.
https://github.com/LiveHelperChat/livehelperchat/commit/ba0018911a4bfd161e9af3620e96992fe502ca40

**Comment by Flash100** [comment]
I still cannot launch a chat on the front end

www.pianowizardacademy.com

It just spins, and if I expand it can see a 500 error sometimes.

**Comment by Joeboyc2** [comment]
Hi Flash100,

Do you have your redirects setup correctly?
Can you browse to the chat interface via its installed directory? Like http://www.pianowizardacademy.com/chat

Joe

**Comment by Flash100** [comment]
conductor.allegrorainbow.com/livehelp/index.php/chat/startchat/(leaveamessage)/true/(theme)/1/(survey)/1/(vid)/0er35xpypf8ifqugv75o/(er)/1?URLReferer=%2F%2Fwww.pianowizardacademy.com%2F

The conductor.allegrorainbow.com page isn’t working
conductor.allegrorainbow.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by Flash100** [comment]
Joe, chat is installed on another domain....not sure where you are asking me to look.

**Comment by Joeboyc2** [comment]
Hi Flash100,

Looks like there is an issue with your URL.

That's destination is not the same Web address you have listed above

**Comment by Flash100** [comment]
https://conductor.allegrorainbow.com/livehelp/index.php/site_admin/theme/adminthemes

is also producing a 500 error.

**Comment by Flash100** [comment]
pianowizardacademy.com is the public site.  That is where the widget is installed.  livehelperchat is installed a conductor.allegrorainbow.com

**Comment by Joeboyc2** [comment]
OK,  I understand a little better now

However that link does work for me and I am presented with the login page

But I am not able to browse to the "chat pages" that should show here: https://conductor.allegrorainbow.com/livehelp

**Comment by Flash100** [comment]
Yea, I can log in fine.  Most of admin works, except for adminthemes.  Visitors are tracking but cannot initiate a chat from pianowizardacademy.com

**Comment by Joeboyc2** [comment]
Seems like there is an issue with the rewrite engine.

What web server are you running? Apache? IIS?

**Comment by Flash100** [comment]
Apache.  The thing is it has been working perfectly for a long time.  All I did was overwrite 2.4.6 just in case there was a newer version (the backend hasn't shown updates for a while) so I guess the ones on github are minor updates not ready for release.  Either way, messed it up.

**Comment by Flash100** [comment]
For example, main page is https://conductor.allegrorainbow.com/livehelp/index.php/site_admin/and that is a rewrite so that works fine.

**Comment by Joeboyc2** [comment]
oh, ok, i assumed this was a fresh install

did the version number change at all? because if it did you may have missed some of the DB SQL scripts that need to be run

that is most likely the issue, i have done this myself in the past where i have jumped version, you always have to run all the DB scripts to ensure it all works after an upgrade

**Comment by Flash100** [comment]
No, version didn't change.  I just overwrite 2.4.6, and as I said, the version is github is different from the original 2.4.6 version...so I should have just left it alone.  Thanks for the help.

**Comment by Flash100** [comment]
As for running ALL the db scripts, I ran upgrade.php...it said DONE.  Not that anything should have changed.

**Comment by Joeboyc2** [comment]
I know this may sound like a silly question. 
But have you tried restoring the files for before the in-place upgrade. 

Failing this I would suggest following the steps outlined here https://livehelperchat.com/old-upgrading-instructions-335a.html

I've never been able to use the update.php file on my site so I would always run the steps manually

Hope this helps

**Comment by Flash100** [comment]
Yes Joe.  Tried that too.  My biggest mistake was not backing up as it really wasn't an upgade...shoulda woulda, never learn.

It's just not making sense why this is fine

https://conductor.allegrorainbow.com/livehelp/index.php/site_admin/theme/defaultadmintheme

and this is 500 error

https://conductor.allegrorainbow.com/livehelp/index.php/site_admin/theme/adminthemes

unless this gitub version is just messed up.

**Comment by Joeboyc2** [comment]
It still sounds to me like the database is missing tables/rows as this type of things has happened to me. But I would get a white screen, not error 500

Have you tried enabling the debug option in the settings file.

And also, have you enable the cross domain and https options?

**Comment by Flash100** [comment]
Yes.
Like you said, the 500 errors are server configuration or bad files and really wouldn't point to database.  I'm wondering if i should open a new ticket since this is marked closed.

**Comment by Joeboyc2** [comment]
Yes that might be a good idea, hopefully Rem can suggest some alternatives

**Comment by Flash100** [comment]
Thanks for the help.  Doing that now.

**Comment by Joeboyc2** [comment]
Flash100,

I've just taken a look at the new issue you have raised, i think you should add more details to it, or link to this discussion. otherwise you may get the same questions i have been asking

**Comment by Flash100** [comment]
Done, thanks again

**Comment by Joeboyc2** [comment]
no worries, hope the community can help you

if you able to think of anything else that may have been done, i mgiht be able to help further.

let us know how you get on,, Good luck
